dubbo:
  scan:
    base-packages: com.sparrow.spring.cloud.alibaba
  protocols:
    dubbo:
      name: dubbo
      port: -1
    rest:
      name: rest
      port: 8088
      server: netty
  registry:
    address: nacos://localhost:8848
#    https://github.com/apache/dubbo/issues/6645 dubbo bug
    use-as-config-center: false
#    parameters:
#        namespace: ${name-space} #名字空间
  consumer:
    timeout: 5000
    check: false
    retries: 0
  cloud:
    subscribed-services: