spring:
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: sparrow-rest
          uri: lb://sparrow-dubbo
          predicates:
            - Path=/api-rest/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=Accept,application/json
            - AddResponseHeader=Accept,application/json
